#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on October 19, 2021 at 18:04:49.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[645];
extern c_float ldata[677];
extern c_float udata[677];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[645];
extern c_float Dinvscaling[645];
extern c_float Escaling[677];
extern c_float Einvscaling[677];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[1322];
extern c_int linsys_solver_P[1322];
extern c_float linsys_solver_bp[1322];
extern c_float linsys_solver_sol[1322];
extern c_float linsys_solver_rho_inv_vec[677];
extern c_int linsys_solver_Pdiag_idx[366];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[366];
extern c_int linsys_solver_AtoKKT[4283];
extern c_int linsys_solver_rhotoKKT[677];
extern QDLDL_float linsys_solver_D[1322];
extern QDLDL_int linsys_solver_etree[1322];
extern QDLDL_int linsys_solver_Lnz[1322];
extern QDLDL_int   linsys_solver_iwork[3966];
extern QDLDL_bool  linsys_solver_bwork[1322];
extern QDLDL_float linsys_solver_fwork[1322];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[645];
extern c_float ysolution[677];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[677];
extern c_float work_rho_inv_vec[677];
extern c_int work_constr_type[677];
extern c_float work_x[645];
extern c_float work_y[677];
extern c_float work_z[677];
extern c_float work_xz_tilde[1322];
extern c_float work_x_prev[645];
extern c_float work_z_prev[677];
extern c_float work_Ax[677];
extern c_float work_Px[645];
extern c_float work_Aty[645];
extern c_float work_delta_y[677];
extern c_float work_Atdelta_y[645];
extern c_float work_delta_x[645];
extern c_float work_Pdelta_x[645];
extern c_float work_Adelta_x[677];
extern c_float work_D_temp[645];
extern c_float work_D_temp_A[645];
extern c_float work_E_temp[677];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
