#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on October 20, 2021 at 16:16:42.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[705];
extern c_float ldata[795];
extern c_float udata[795];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[705];
extern c_float Dinvscaling[705];
extern c_float Escaling[795];
extern c_float Einvscaling[795];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[1500];
extern c_int linsys_solver_P[1500];
extern c_float linsys_solver_bp[1500];
extern c_float linsys_solver_sol[1500];
extern c_float linsys_solver_rho_inv_vec[795];
extern c_int linsys_solver_Pdiag_idx[366];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[366];
extern c_int linsys_solver_AtoKKT[4521];
extern c_int linsys_solver_rhotoKKT[795];
extern QDLDL_float linsys_solver_D[1500];
extern QDLDL_int linsys_solver_etree[1500];
extern QDLDL_int linsys_solver_Lnz[1500];
extern QDLDL_int   linsys_solver_iwork[4500];
extern QDLDL_bool  linsys_solver_bwork[1500];
extern QDLDL_float linsys_solver_fwork[1500];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[705];
extern c_float ysolution[795];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[795];
extern c_float work_rho_inv_vec[795];
extern c_int work_constr_type[795];
extern c_float work_x[705];
extern c_float work_y[795];
extern c_float work_z[795];
extern c_float work_xz_tilde[1500];
extern c_float work_x_prev[705];
extern c_float work_z_prev[795];
extern c_float work_Ax[795];
extern c_float work_Px[705];
extern c_float work_Aty[705];
extern c_float work_delta_y[795];
extern c_float work_Atdelta_y[705];
extern c_float work_delta_x[705];
extern c_float work_Pdelta_x[705];
extern c_float work_Adelta_x[795];
extern c_float work_D_temp[705];
extern c_float work_D_temp_A[705];
extern c_float work_E_temp[795];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
